lock_url: 'https://cdn.auth0.com/js/lock/10.8/lock.min.js'
lock_passwordless_url: 'https://cdn.auth0.com/js/lock-passwordless-2.2.min.js'
auth0js_url: 'https://cdn.auth0.com/js/auth0/8.0.4/auth0.min.js'
